// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { createHealthCheckHealthPost, getMeAuthMeGet, getMyStatsApiMeStatsGet, getMyWeaknessApiMeWeaknessGet, getProblemDetailApiProblemsProblemIdGet, getProblemGenerationStatusApiProblemsGenerateRequestIdGet, getSubmissionApiSubmissionsSubmissionIdGet, githubCallbackAuthGithubCallbackGet, healthzHealthzGet, listHealthChecksHealthGet, listMySubmissionsApiSubmissionsGet, listProblemsApiProblemsGet, logoutAuthLogoutPost, type Options, requestProblemGenerationApiProblemsGeneratePost, startGithubOauthAuthGithubGet, submitAnswerApiSubmissionsPost } from '../sdk.gen';
import type { CreateHealthCheckHealthPostData, CreateHealthCheckHealthPostResponse, GetMeAuthMeGetData, GetMeAuthMeGetResponse, GetMyStatsApiMeStatsGetData, GetMyStatsApiMeStatsGetResponse, GetMyWeaknessApiMeWeaknessGetData, GetMyWeaknessApiMeWeaknessGetResponse, GetProblemDetailApiProblemsProblemIdGetData, GetProblemDetailApiProblemsProblemIdGetError, GetProblemDetailApiProblemsProblemIdGetResponse, GetProblemGenerationStatusApiProblemsGenerateRequestIdGetData, GetProblemGenerationStatusApiProblemsGenerateRequestIdGetError, GetProblemGenerationStatusApiProblemsGenerateRequestIdGetResponse, GetSubmissionApiSubmissionsSubmissionIdGetData, GetSubmissionApiSubmissionsSubmissionIdGetError, GetSubmissionApiSubmissionsSubmissionIdGetResponse, GithubCallbackAuthGithubCallbackGetData, GithubCallbackAuthGithubCallbackGetError, HealthzHealthzGetData, HealthzHealthzGetResponse, ListHealthChecksHealthGetData, ListHealthChecksHealthGetResponse, ListMySubmissionsApiSubmissionsGetData, ListMySubmissionsApiSubmissionsGetError, ListMySubmissionsApiSubmissionsGetResponse, ListProblemsApiProblemsGetData, ListProblemsApiProblemsGetError, ListProblemsApiProblemsGetResponse, LogoutAuthLogoutPostData, LogoutAuthLogoutPostResponse, RequestProblemGenerationApiProblemsGeneratePostData, RequestProblemGenerationApiProblemsGeneratePostError, RequestProblemGenerationApiProblemsGeneratePostResponse, StartGithubOauthAuthGithubGetData, StartGithubOauthAuthGithubGetError, SubmitAnswerApiSubmissionsPostData, SubmitAnswerApiSubmissionsPostError, SubmitAnswerApiSubmissionsPostResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getMyStatsApiMeStatsGetQueryKey = (options?: Options<GetMyStatsApiMeStatsGetData>) => createQueryKey('getMyStatsApiMeStatsGet', options);

/**
 * Get My Stats
 *
 * 全期間・全カテゴリの正答率を返す（取得時点でリアルタイム集計）。
 *
 * - 採点完了行（status='graded'）のみカウント
 * - 履歴ゼロのユーザーには total=0 / accuracy=0.0 / byCategory=[] を返す
 * - ソフトデリートは無視（履歴永続保存、learning.md §ビジネスルール）
 */
export const getMyStatsApiMeStatsGetOptions = (options?: Options<GetMyStatsApiMeStatsGetData>) => queryOptions<GetMyStatsApiMeStatsGetResponse, DefaultError, GetMyStatsApiMeStatsGetResponse, ReturnType<typeof getMyStatsApiMeStatsGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getMyStatsApiMeStatsGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getMyStatsApiMeStatsGetQueryKey(options)
});

export const getMyWeaknessApiMeWeaknessGetQueryKey = (options?: Options<GetMyWeaknessApiMeWeaknessGetData>) => createQueryKey('getMyWeaknessApiMeWeaknessGet', options);

/**
 * Get My Weakness
 *
 * 正答率の低いカテゴリ Top N を返す。
 *
 * 抽出ルール（learning.md §ビジネスルール）：
 * - 3 問以上解答かつ正答率 50% 未満のカテゴリのみ対象
 * - accuracy 昇順、tie-break で attempts 降順
 * - Top 5 まで返す
 */
export const getMyWeaknessApiMeWeaknessGetOptions = (options?: Options<GetMyWeaknessApiMeWeaknessGetData>) => queryOptions<GetMyWeaknessApiMeWeaknessGetResponse, DefaultError, GetMyWeaknessApiMeWeaknessGetResponse, ReturnType<typeof getMyWeaknessApiMeWeaknessGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getMyWeaknessApiMeWeaknessGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getMyWeaknessApiMeWeaknessGetQueryKey(options)
});

export const listProblemsApiProblemsGetQueryKey = (options?: Options<ListProblemsApiProblemsGetData>) => createQueryKey('listProblemsApiProblemsGet', options);

/**
 * List Problems
 *
 * カテゴリ・難易度フィルタ付きで問題一覧を返す。
 *
 * - 認証不要（ゲスト閲覧可、problem-display-and-answer.md §ビジネスルール）
 * - 並び順は created_at DESC（新着優先）
 * - 0 件でも 200 + items=[] / totalPages=0 で返す
 */
export const listProblemsApiProblemsGetOptions = (options?: Options<ListProblemsApiProblemsGetData>) => queryOptions<ListProblemsApiProblemsGetResponse, ListProblemsApiProblemsGetError, ListProblemsApiProblemsGetResponse, ReturnType<typeof listProblemsApiProblemsGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listProblemsApiProblemsGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listProblemsApiProblemsGetQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const listProblemsApiProblemsGetInfiniteQueryKey = (options?: Options<ListProblemsApiProblemsGetData>): QueryKey<Options<ListProblemsApiProblemsGetData>> => createQueryKey('listProblemsApiProblemsGet', options, true);

/**
 * List Problems
 *
 * カテゴリ・難易度フィルタ付きで問題一覧を返す。
 *
 * - 認証不要（ゲスト閲覧可、problem-display-and-answer.md §ビジネスルール）
 * - 並び順は created_at DESC（新着優先）
 * - 0 件でも 200 + items=[] / totalPages=0 で返す
 */
export const listProblemsApiProblemsGetInfiniteOptions = (options?: Options<ListProblemsApiProblemsGetData>) => infiniteQueryOptions<ListProblemsApiProblemsGetResponse, ListProblemsApiProblemsGetError, InfiniteData<ListProblemsApiProblemsGetResponse>, QueryKey<Options<ListProblemsApiProblemsGetData>>, number | Pick<QueryKey<Options<ListProblemsApiProblemsGetData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<ListProblemsApiProblemsGetData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                page: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await listProblemsApiProblemsGet({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listProblemsApiProblemsGetInfiniteQueryKey(options)
});

/**
 * Request Problem Generation
 *
 * カテゴリ・難易度を受け取って生成ジョブを enqueue する。
 *
 * 挙動：
 * - generation_requests へ 1 行 INSERT（status='pending'）
 * - jobs へ 1 行 INSERT + NOTIFY new_job を同一トランザクションで実行
 * - 202 で requestId を返す。実際の生成は Worker が非同期で処理する
 * - レート制限: 同一ユーザーで 1 分 / 5 回を超えると 429 を返す
 */
export const requestProblemGenerationApiProblemsGeneratePostMutation = (options?: Partial<Options<RequestProblemGenerationApiProblemsGeneratePostData>>): UseMutationOptions<RequestProblemGenerationApiProblemsGeneratePostResponse, RequestProblemGenerationApiProblemsGeneratePostError, Options<RequestProblemGenerationApiProblemsGeneratePostData>> => {
    const mutationOptions: UseMutationOptions<RequestProblemGenerationApiProblemsGeneratePostResponse, RequestProblemGenerationApiProblemsGeneratePostError, Options<RequestProblemGenerationApiProblemsGeneratePostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await requestProblemGenerationApiProblemsGeneratePost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getProblemGenerationStatusApiProblemsGenerateRequestIdGetQueryKey = (options: Options<GetProblemGenerationStatusApiProblemsGenerateRequestIdGetData>) => createQueryKey('getProblemGenerationStatusApiProblemsGenerateRequestIdGet', options);

/**
 * Get Problem Generation Status
 *
 * 生成リクエストの現在ステータスを返す。
 *
 * - 自分のリクエストでない / 存在しないリクエスト ID には 404 を返す
 * （他人のリクエストか存在しないかの区別は付けない、情報漏洩防止）
 * - status='completed' の時のみ problemId フィールドが付く
 */
export const getProblemGenerationStatusApiProblemsGenerateRequestIdGetOptions = (options: Options<GetProblemGenerationStatusApiProblemsGenerateRequestIdGetData>) => queryOptions<GetProblemGenerationStatusApiProblemsGenerateRequestIdGetResponse, GetProblemGenerationStatusApiProblemsGenerateRequestIdGetError, GetProblemGenerationStatusApiProblemsGenerateRequestIdGetResponse, ReturnType<typeof getProblemGenerationStatusApiProblemsGenerateRequestIdGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getProblemGenerationStatusApiProblemsGenerateRequestIdGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getProblemGenerationStatusApiProblemsGenerateRequestIdGetQueryKey(options)
});

export const getProblemDetailApiProblemsProblemIdGetQueryKey = (options: Options<GetProblemDetailApiProblemsProblemIdGetData>) => createQueryKey('getProblemDetailApiProblemsProblemIdGet', options);

/**
 * Get Problem Detail
 *
 * 問題詳細を返す。テストケース全体は返さず examples（公開用 1〜数件）のみ含む。
 *
 * - 認証不要（problem-display-and-answer.md §ビジネスルール）
 * - 存在しない / ソフトデリート済みは 404
 * - レスポンスから test_cases / reference_solution / judge_scores を完全に
 * 落とすマスキングは ProblemDetailResponse のスキーマ定義で実施される
 */
export const getProblemDetailApiProblemsProblemIdGetOptions = (options: Options<GetProblemDetailApiProblemsProblemIdGetData>) => queryOptions<GetProblemDetailApiProblemsProblemIdGetResponse, GetProblemDetailApiProblemsProblemIdGetError, GetProblemDetailApiProblemsProblemIdGetResponse, ReturnType<typeof getProblemDetailApiProblemsProblemIdGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getProblemDetailApiProblemsProblemIdGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getProblemDetailApiProblemsProblemIdGetQueryKey(options)
});

export const listMySubmissionsApiSubmissionsGetQueryKey = (options?: Options<ListMySubmissionsApiSubmissionsGetData>) => createQueryKey('listMySubmissionsApiSubmissionsGet', options);

/**
 * List My Submissions
 *
 * 自分の解答履歴をページングで返す。
 *
 * 並び順は created_at DESC（新着順）。problem_title まで含めて返すため
 * 一覧 UI 側は追加の問題詳細取得が不要。
 */
export const listMySubmissionsApiSubmissionsGetOptions = (options?: Options<ListMySubmissionsApiSubmissionsGetData>) => queryOptions<ListMySubmissionsApiSubmissionsGetResponse, ListMySubmissionsApiSubmissionsGetError, ListMySubmissionsApiSubmissionsGetResponse, ReturnType<typeof listMySubmissionsApiSubmissionsGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listMySubmissionsApiSubmissionsGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listMySubmissionsApiSubmissionsGetQueryKey(options)
});

export const listMySubmissionsApiSubmissionsGetInfiniteQueryKey = (options?: Options<ListMySubmissionsApiSubmissionsGetData>): QueryKey<Options<ListMySubmissionsApiSubmissionsGetData>> => createQueryKey('listMySubmissionsApiSubmissionsGet', options, true);

/**
 * List My Submissions
 *
 * 自分の解答履歴をページングで返す。
 *
 * 並び順は created_at DESC（新着順）。problem_title まで含めて返すため
 * 一覧 UI 側は追加の問題詳細取得が不要。
 */
export const listMySubmissionsApiSubmissionsGetInfiniteOptions = (options?: Options<ListMySubmissionsApiSubmissionsGetData>) => infiniteQueryOptions<ListMySubmissionsApiSubmissionsGetResponse, ListMySubmissionsApiSubmissionsGetError, InfiniteData<ListMySubmissionsApiSubmissionsGetResponse>, QueryKey<Options<ListMySubmissionsApiSubmissionsGetData>>, number | Pick<QueryKey<Options<ListMySubmissionsApiSubmissionsGetData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<ListMySubmissionsApiSubmissionsGetData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                page: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await listMySubmissionsApiSubmissionsGet({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listMySubmissionsApiSubmissionsGetInfiniteQueryKey(options)
});

/**
 * Submit Answer
 *
 * 解答コードを受け付けて submissions 行を作成し、202 で submissionId を返す。
 *
 * 挙動：
 * - 対象問題の存在確認（存在しない / soft delete 済みは 404）
 * - submissions に 1 行 INSERT（status='pending'）
 * - 同一トランザクション内で jobs に 1 行 INSERT + NOTIFY new_job
 * - レート制限: 1 ユーザー 1 分 / 20 回まで
 *
 * クライアントはレスポンスの submissionId を持って
 * GET /api/submissions/:id をポーリングし、status が graded / failed に遷移するのを待つ。
 */
export const submitAnswerApiSubmissionsPostMutation = (options?: Partial<Options<SubmitAnswerApiSubmissionsPostData>>): UseMutationOptions<SubmitAnswerApiSubmissionsPostResponse, SubmitAnswerApiSubmissionsPostError, Options<SubmitAnswerApiSubmissionsPostData>> => {
    const mutationOptions: UseMutationOptions<SubmitAnswerApiSubmissionsPostResponse, SubmitAnswerApiSubmissionsPostError, Options<SubmitAnswerApiSubmissionsPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await submitAnswerApiSubmissionsPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getSubmissionApiSubmissionsSubmissionIdGetQueryKey = (options: Options<GetSubmissionApiSubmissionsSubmissionIdGetData>) => createQueryKey('getSubmissionApiSubmissionsSubmissionIdGet', options);

/**
 * Get Submission
 *
 * 採点状態 + 結果を返す。
 *
 * - pending の間は score / totalCount / result / gradedAt が None
 * - graded / failed に遷移してから埋まる（Worker が UPDATE）
 * - 他人の id や存在しない id は 404
 */
export const getSubmissionApiSubmissionsSubmissionIdGetOptions = (options: Options<GetSubmissionApiSubmissionsSubmissionIdGetData>) => queryOptions<GetSubmissionApiSubmissionsSubmissionIdGetResponse, GetSubmissionApiSubmissionsSubmissionIdGetError, GetSubmissionApiSubmissionsSubmissionIdGetResponse, ReturnType<typeof getSubmissionApiSubmissionsSubmissionIdGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getSubmissionApiSubmissionsSubmissionIdGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getSubmissionApiSubmissionsSubmissionIdGetQueryKey(options)
});

export const startGithubOauthAuthGithubGetQueryKey = (options?: Options<StartGithubOauthAuthGithubGetData>) => createQueryKey('startGithubOauthAuthGithubGet', options);

/**
 * Start Github Oauth
 *
 * OAuth フロー開始。state を発行し GitHub の認可画面へ 302 リダイレクトする。
 *
 * クエリ:
 * - next: ログイン後の戻り先（同一オリジン相対パスのみ）。state レコードに
 * 同梱して Redis に保存し、callback 側で 1 回使い切りで取り出す。
 * 旧実装は別 Cookie（auth_next）で運んでいたが「state と next が
 * 別場所に分かれて弱く結合」する設計弱点があったため state レコード
 * 側に集約した。
 */
export const startGithubOauthAuthGithubGetOptions = (options?: Options<StartGithubOauthAuthGithubGetData>) => queryOptions<unknown, StartGithubOauthAuthGithubGetError, unknown, ReturnType<typeof startGithubOauthAuthGithubGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await startGithubOauthAuthGithubGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: startGithubOauthAuthGithubGetQueryKey(options)
});

export const githubCallbackAuthGithubCallbackGetQueryKey = (options?: Options<GithubCallbackAuthGithubCallbackGetData>) => createQueryKey('githubCallbackAuthGithubCallbackGet', options);

/**
 * Github Callback
 *
 * GitHub からのコールバック。
 *
 * 成功時：Set-Cookie で sid / csrf_token を発行してホーム（または ?next= 指定先）へ 302。
 * state 不一致 / 期限切れ / 再使用：/login?auth_error=state_invalid へ 302。
 * GitHub が ?error= を返した時：/login?auth_error=oauth_canceled へ 302。
 * その他例外：/login?auth_error=oauth_failed へ 302。
 */
export const githubCallbackAuthGithubCallbackGetOptions = (options?: Options<GithubCallbackAuthGithubCallbackGetData>) => queryOptions<unknown, GithubCallbackAuthGithubCallbackGetError, unknown, ReturnType<typeof githubCallbackAuthGithubCallbackGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await githubCallbackAuthGithubCallbackGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: githubCallbackAuthGithubCallbackGetQueryKey(options)
});

/**
 * Logout
 *
 * セッションを破棄し、Cookie を Max-Age=0 で消す。
 *
 * - 内部的に Redis から `session:<sid>` を DELETE + `user:<id>:sessions` から SREM
 * - 204 No Content（ボディなし）。Cookie だけがレスポンスヘッダーに残る
 */
export const logoutAuthLogoutPostMutation = (options?: Partial<Options<LogoutAuthLogoutPostData>>): UseMutationOptions<LogoutAuthLogoutPostResponse, DefaultError, Options<LogoutAuthLogoutPostData>> => {
    const mutationOptions: UseMutationOptions<LogoutAuthLogoutPostResponse, DefaultError, Options<LogoutAuthLogoutPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await logoutAuthLogoutPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getMeAuthMeGetQueryKey = (options?: Options<GetMeAuthMeGetData>) => createQueryKey('getMeAuthMeGet', options);

/**
 * Get Me
 *
 * ログイン中のユーザー情報を返す。未認証なら 401（get_current_user が投げる）。
 */
export const getMeAuthMeGetOptions = (options?: Options<GetMeAuthMeGetData>) => queryOptions<GetMeAuthMeGetResponse, DefaultError, GetMeAuthMeGetResponse, ReturnType<typeof getMeAuthMeGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getMeAuthMeGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getMeAuthMeGetQueryKey(options)
});

export const listHealthChecksHealthGetQueryKey = (options?: Options<ListHealthChecksHealthGetData>) => createQueryKey('listHealthChecksHealthGet', options);

/**
 * List Health Checks
 *
 * 直近 10 件を新しい順に返す。
 */
export const listHealthChecksHealthGetOptions = (options?: Options<ListHealthChecksHealthGetData>) => queryOptions<ListHealthChecksHealthGetResponse, DefaultError, ListHealthChecksHealthGetResponse, ReturnType<typeof listHealthChecksHealthGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listHealthChecksHealthGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listHealthChecksHealthGetQueryKey(options)
});

/**
 * Create Health Check
 *
 * DB に 1 行追加して、追加した行を返す。
 */
export const createHealthCheckHealthPostMutation = (options?: Partial<Options<CreateHealthCheckHealthPostData>>): UseMutationOptions<CreateHealthCheckHealthPostResponse, DefaultError, Options<CreateHealthCheckHealthPostData>> => {
    const mutationOptions: UseMutationOptions<CreateHealthCheckHealthPostResponse, DefaultError, Options<CreateHealthCheckHealthPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createHealthCheckHealthPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const healthzHealthzGetQueryKey = (options?: Options<HealthzHealthzGetData>) => createQueryKey('healthzHealthzGet', options);

/**
 * Healthz
 *
 * liveness probe（DB 接続なし）。プロセスが生きていることだけを返す。
 */
export const healthzHealthzGetOptions = (options?: Options<HealthzHealthzGetData>) => queryOptions<HealthzHealthzGetResponse, DefaultError, HealthzHealthzGetResponse, ReturnType<typeof healthzHealthzGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await healthzHealthzGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: healthzHealthzGetQueryKey(options)
});
