"""add problems list partial index for R1-4

Revision ID: ae67f52f4cc6
Revises: 1d8a244b8bd8
Create Date: 2026-05-21 00:47:37.464023

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ae67f52f4cc6"
down_revision: str | Sequence[str] | None = "1d8a244b8bd8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_problems_category_difficulty_created_at_active",
        "problems",
        ["category", "difficulty", sa.literal_column("created_at DESC")],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_problems_category_difficulty_created_at_active",
        table_name="problems",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # ### end Alembic commands ###
