// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateHealthCheckHealthPostData, CreateHealthCheckHealthPostResponses, GetMeAuthMeGetData, GetMeAuthMeGetResponses, GithubCallbackAuthGithubCallbackGetData, GithubCallbackAuthGithubCallbackGetErrors, HealthzHealthzGetData, HealthzHealthzGetResponses, ListHealthChecksHealthGetData, ListHealthChecksHealthGetResponses, LogoutAuthLogoutPostData, LogoutAuthLogoutPostResponses, StartGithubOauthAuthGithubGetData, StartGithubOauthAuthGithubGetErrors } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Start Github Oauth
 *
 * OAuth フロー開始。state を発行し GitHub の認可画面へ 302 リダイレクトする。
 *
 * クエリ:
 * - next: ログイン後の戻り先（同一オリジン相対パスのみ）。callback 時に使うため
 * state と一緒に Redis に格納する… のが理想だが、現状の state_store は
 * 値を持たない設計のため、Cookie に一時格納する方式を取る（HttpOnly + Lax）。
 */
export const startGithubOauthAuthGithubGet = <ThrowOnError extends boolean = false>(options?: Options<StartGithubOauthAuthGithubGetData, ThrowOnError>) => (options?.client ?? client).get<unknown, StartGithubOauthAuthGithubGetErrors, ThrowOnError>({ url: '/auth/github', ...options });

/**
 * Github Callback
 *
 * GitHub からのコールバック。
 *
 * 成功時：Set-Cookie で sid / csrf_token を発行してホーム（または ?next= 指定先）へ 302。
 * state 不一致 / 期限切れ / 再使用：/login?auth_error=state_invalid へ 302。
 * GitHub が ?error= を返した時：/login?auth_error=oauth_canceled へ 302。
 * その他例外：/login?auth_error=oauth_failed へ 302。
 */
export const githubCallbackAuthGithubCallbackGet = <ThrowOnError extends boolean = false>(options?: Options<GithubCallbackAuthGithubCallbackGetData, ThrowOnError>) => (options?.client ?? client).get<unknown, GithubCallbackAuthGithubCallbackGetErrors, ThrowOnError>({ url: '/auth/github/callback', ...options });

/**
 * Logout
 *
 * セッションを破棄し、Cookie を Max-Age=0 で消す。
 *
 * - 内部的に Redis から `session:<sid>` を DELETE + `user:<id>:sessions` から SREM
 * - 204 No Content（ボディなし）。Cookie だけがレスポンスヘッダーに残る
 */
export const logoutAuthLogoutPost = <ThrowOnError extends boolean = false>(options?: Options<LogoutAuthLogoutPostData, ThrowOnError>) => (options?.client ?? client).post<LogoutAuthLogoutPostResponses, unknown, ThrowOnError>({ url: '/auth/logout', ...options });

/**
 * Get Me
 *
 * ログイン中のユーザー情報を返す。未認証なら 401（get_current_user が投げる）。
 */
export const getMeAuthMeGet = <ThrowOnError extends boolean = false>(options?: Options<GetMeAuthMeGetData, ThrowOnError>) => (options?.client ?? client).get<GetMeAuthMeGetResponses, unknown, ThrowOnError>({ url: '/auth/me', ...options });

/**
 * List Health Checks
 *
 * 直近 10 件を新しい順に返す。
 */
export const listHealthChecksHealthGet = <ThrowOnError extends boolean = false>(options?: Options<ListHealthChecksHealthGetData, ThrowOnError>) => (options?.client ?? client).get<ListHealthChecksHealthGetResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * Create Health Check
 *
 * DB に 1 行追加して、追加した行を返す。
 */
export const createHealthCheckHealthPost = <ThrowOnError extends boolean = false>(options?: Options<CreateHealthCheckHealthPostData, ThrowOnError>) => (options?.client ?? client).post<CreateHealthCheckHealthPostResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * Healthz
 *
 * liveness probe（DB 接続なし）。プロセスが生きていることだけを返す。
 */
export const healthzHealthzGet = <ThrowOnError extends boolean = false>(options?: Options<HealthzHealthzGetData, ThrowOnError>) => (options?.client ?? client).get<HealthzHealthzGetResponses, unknown, ThrowOnError>({ url: '/healthz', ...options });
