// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateHealthCheckHealthPostData, CreateHealthCheckHealthPostResponses, HealthzHealthzGetData, HealthzHealthzGetResponses, ListHealthChecksHealthGetData, ListHealthChecksHealthGetResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List Health Checks
 *
 * 直近 10 件を新しい順に返す。
 */
export const listHealthChecksHealthGet = <ThrowOnError extends boolean = false>(options?: Options<ListHealthChecksHealthGetData, ThrowOnError>) => (options?.client ?? client).get<ListHealthChecksHealthGetResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * Create Health Check
 *
 * DB に 1 行追加して、追加した行を返す。
 */
export const createHealthCheckHealthPost = <ThrowOnError extends boolean = false>(options?: Options<CreateHealthCheckHealthPostData, ThrowOnError>) => (options?.client ?? client).post<CreateHealthCheckHealthPostResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * Healthz
 *
 * liveness probe（DB 接続なし）。プロセスが生きていることだけを返す。
 */
export const healthzHealthzGet = <ThrowOnError extends boolean = false>(options?: Options<HealthzHealthzGetData, ThrowOnError>) => (options?.client ?? client).get<HealthzHealthzGetResponses, unknown, ThrowOnError>({ url: '/healthz', ...options });
