// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AttemptError
 *
 * 1 回分の試行エラー（jobs.attempt_errors の 1 要素）。
 */
export type AttemptError = {
    /**
     * Attempt
     */
    attempt: number;
    /**
     * Failedat
     */
    failedAt: string;
    /**
     * Failurereason
     */
    failureReason: 'llm_unauthorized' | 'llm_cost_exceeded' | 'judge_below_threshold' | 'sandbox_failed' | 'sandbox_infrastructure' | 'llm_invalid_output' | 'llm_rate_limit' | 'llm_timeout' | 'llm_schema_invalid' | 'max_attempts_exceeded';
    /**
     * Message
     */
    message: string;
};

/**
 * GenerationRequestCancelResponse
 *
 * キャンセル後の最終状態。
 */
export type GenerationRequestCancelResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Status
     */
    status: 'canceled';
};

/**
 * GenerationRequestRetryResponse
 *
 * 再試行で作られた新規 generation_request の最小情報。
 */
export type GenerationRequestRetryResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Retryof
     */
    retryOf: string;
    /**
     * Status
     */
    status: 'pending';
};

/**
 * GenerationRequestSummary
 *
 * 生成リクエスト履歴の 1 行分。
 */
export type GenerationRequestSummary = {
    /**
     * Attempterrors
     */
    attemptErrors?: Array<AttemptError>;
    /**
     * Category
     */
    category: string;
    /**
     * Completedat
     */
    completedAt?: string | null;
    /**
     * Createdat
     */
    createdAt: string;
    /**
     * Difficulty
     */
    difficulty: string;
    /**
     * Failurereason
     */
    failureReason?: 'llm_unauthorized' | 'llm_cost_exceeded' | 'judge_below_threshold' | 'sandbox_failed' | 'sandbox_infrastructure' | 'llm_invalid_output' | 'llm_rate_limit' | 'llm_timeout' | 'llm_schema_invalid' | 'max_attempts_exceeded' | null;
    /**
     * Id
     */
    id: string;
    /**
     * Producedproblemid
     */
    producedProblemId?: string | null;
    /**
     * Progressstep
     */
    progressStep?: 'llm_generating' | 'sandbox_verifying' | 'judging' | 'persisting' | null;
    /**
     * Promptversion
     */
    promptVersion?: string | null;
    /**
     * Retrycount
     */
    retryCount: number;
    /**
     * Retryof
     */
    retryOf?: string | null;
    /**
     * Status
     */
    status: 'pending' | 'completed' | 'failed' | 'canceled';
};

/**
 * GenerationStatus
 */
export type GenerationStatus = 'pending' | 'completed' | 'failed';

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthCheckResponse
 */
export type HealthCheckResponse = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Id
     */
    id: string;
};

/**
 * MeCategoryStat
 *
 * カテゴリ別の解答数・正解数・正答率。
 */
export type MeCategoryStat = {
    /**
     * Accuracy
     */
    accuracy: number;
    /**
     * Attempts
     */
    attempts: number;
    /**
     * Category
     */
    category: string;
    /**
     * Correct
     */
    correct: number;
};

/**
 * MeGenerationsListResponse
 *
 * 生成履歴一覧 + ページネーション情報。
 */
export type MeGenerationsListResponse = {
    /**
     * Items
     */
    items: Array<GenerationRequestSummary>;
    /**
     * Page
     */
    page: number;
    /**
     * Pagesize
     */
    pageSize: number;
    /**
     * Totalpages
     */
    totalPages: number;
};

/**
 * MeStatsResponse
 *
 * 全期間の正答率 + カテゴリ別習熟度。
 */
export type MeStatsResponse = {
    /**
     * Accuracy
     */
    accuracy: number;
    /**
     * Bycategory
     */
    byCategory: Array<MeCategoryStat>;
    /**
     * Correct
     */
    correct: number;
    /**
     * Total
     */
    total: number;
};

/**
 * MeWeakCategoryItem
 *
 * 弱点に該当するカテゴリ 1 件。
 */
export type MeWeakCategoryItem = {
    /**
     * Accuracy
     */
    accuracy: number;
    /**
     * Attempts
     */
    attempts: number;
    /**
     * Category
     */
    category: string;
    /**
     * Correct
     */
    correct: number;
};

/**
 * MeWeaknessResponse
 *
 * 弱点カテゴリ Top N。
 */
export type MeWeaknessResponse = {
    /**
     * Weakcategories
     */
    weakCategories: Array<MeWeakCategoryItem>;
};

/**
 * ProblemCategory
 */
export type ProblemCategory = 'string' | 'array' | 'recursion' | 'async' | 'type-puzzle';

/**
 * ProblemDetailResponse
 *
 * 問題詳細。テストケースの一部のみ examples として公開する。
 */
export type ProblemDetailResponse = {
    category: ProblemCategory;
    /**
     * Description
     */
    description: string;
    difficulty: ProblemDifficulty;
    /**
     * Examples
     */
    examples: Array<ProblemExample>;
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
};

/**
 * ProblemDifficulty
 */
export type ProblemDifficulty = 'easy' | 'medium' | 'hard';

/**
 * ProblemExample
 *
 * 画面表示用の入出力例。input / output は表示用の文字列。
 */
export type ProblemExample = {
    /**
     * Input
     */
    input: string;
    /**
     * Output
     */
    output: string;
};

/**
 * ProblemGenerateAcceptedResponse
 *
 * 生成リクエスト受付完了。クライアントは requestId でポーリングを始める。
 */
export type ProblemGenerateAcceptedResponse = {
    /**
     * Requestid
     */
    requestId: string;
    /**
     * Status
     */
    status?: 'pending';
};

/**
 * ProblemGenerateRequest
 *
 * 問題生成リクエストの入力。
 *
 * category / difficulty とも Literal 縛りで MVP の許容値以外は 422 を返す
 * （バリデーションは Pydantic が SSoT、problem-generation.md §バリデーション）。
 */
export type ProblemGenerateRequest = {
    category: ProblemCategory;
    difficulty: ProblemDifficulty;
};

/**
 * ProblemGenerateStatusResponse
 *
 * 生成リクエストの現在ステータス。completed の時のみ problemId を含む。
 */
export type ProblemGenerateStatusResponse = {
    /**
     * Attempterrors
     */
    attemptErrors?: Array<AttemptError>;
    /**
     * Completedat
     */
    completedAt?: string | null;
    /**
     * Createdat
     */
    createdAt?: string | null;
    /**
     * Failurereason
     */
    failureReason?: 'llm_unauthorized' | 'llm_cost_exceeded' | 'judge_below_threshold' | 'sandbox_failed' | 'sandbox_infrastructure' | 'llm_invalid_output' | 'llm_rate_limit' | 'llm_timeout' | 'llm_schema_invalid' | 'max_attempts_exceeded' | null;
    /**
     * Problemid
     */
    problemId?: string | null;
    /**
     * Progressstep
     */
    progressStep?: 'llm_generating' | 'sandbox_verifying' | 'judging' | 'persisting' | null;
    /**
     * Requestid
     */
    requestId: string;
    status: GenerationStatus;
};

/**
 * ProblemListResponse
 *
 * 問題一覧 + ページネーション情報。
 *
 * 一覧クエリ単発で SSoT が固定されており、PaginationMeta + Page の
 * 汎用化（backend.md 推奨）は 2 つ目の paginated エンドポイントが
 * 出てきた時点で行う（YAGNI、CLAUDE.md §設計原則）。
 */
export type ProblemListResponse = {
    /**
     * Items
     */
    items: Array<ProblemSummaryResponse>;
    /**
     * Page
     */
    page: number;
    /**
     * Totalpages
     */
    totalPages: number;
};

/**
 * ProblemSummaryResponse
 *
 * 問題一覧の 1 行分。タイトル / カテゴリ / 難易度のみで一覧 UI に必要十分。
 */
export type ProblemSummaryResponse = {
    category: ProblemCategory;
    difficulty: ProblemDifficulty;
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
};

/**
 * SubmissionAcceptedResponse
 *
 * 解答送信の受付完了。クライアントは submissionId を持って結果取得 API を叩く。
 */
export type SubmissionAcceptedResponse = {
    /**
     * Status
     */
    status?: 'pending';
    /**
     * Submissionid
     */
    submissionId: string;
};

/**
 * SubmissionCreateRequest
 *
 * 解答送信リクエスト。
 */
export type SubmissionCreateRequest = {
    /**
     * Code
     */
    code: string;
    /**
     * Problemid
     */
    problemId: string;
};

/**
 * SubmissionFailureKind
 */
export type SubmissionFailureKind = 'test_failed' | 'timeout' | 'oom' | 'syntax' | 'runtime' | 'type_error';

/**
 * SubmissionResultPayload
 *
 * 採点完了時の結果ペイロード。Worker が submissions.result に書き込む形と一致。
 */
export type SubmissionResultPayload = {
    /**
     * Durationms
     */
    durationMs: number;
    failureKind?: SubmissionFailureKind | null;
    /**
     * Passed
     */
    passed: boolean;
    /**
     * Testresults
     */
    testResults?: Array<SubmissionTestResultItem>;
};

/**
 * SubmissionStatus
 */
export type SubmissionStatus = 'pending' | 'graded' | 'failed';

/**
 * SubmissionStatusResponse
 *
 * 解答 + 採点結果。クライアントは pending の間ポーリングする。
 */
export type SubmissionStatusResponse = {
    /**
     * Gradedat
     */
    gradedAt?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Problemid
     */
    problemId: string;
    result?: SubmissionResultPayload | null;
    /**
     * Score
     */
    score?: number | null;
    status: SubmissionStatus;
    /**
     * Totalcount
     */
    totalCount?: number | null;
};

/**
 * SubmissionSummary
 *
 * 解答履歴の 1 行分。問題タイトルまで含めて一覧 UI に必要十分。
 */
export type SubmissionSummary = {
    /**
     * Gradedat
     */
    gradedAt?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Problemid
     */
    problemId: string;
    /**
     * Problemtitle
     */
    problemTitle: string;
    /**
     * Score
     */
    score?: number | null;
    status: SubmissionStatus;
    /**
     * Totalcount
     */
    totalCount?: number | null;
};

/**
 * SubmissionTestResultItem
 *
 * 1 テストケース分の結果。passed=false の時に expected/actual/message が埋まる。
 */
export type SubmissionTestResultItem = {
    /**
     * Actual
     */
    actual?: string | null;
    /**
     * Durationms
     */
    durationMs: number;
    /**
     * Expected
     */
    expected?: string | null;
    /**
     * Message
     */
    message?: string | null;
    /**
     * Name
     */
    name: string;
    /**
     * Passed
     */
    passed: boolean;
};

/**
 * SubmissionsListResponse
 *
 * 解答履歴一覧 + ページネーション情報。
 */
export type SubmissionsListResponse = {
    /**
     * Items
     */
    items: Array<SubmissionSummary>;
    /**
     * Page
     */
    page: number;
    /**
     * Pagesize
     */
    pageSize: number;
    /**
     * Totalpages
     */
    totalPages: number;
};

/**
 * UserResponse
 *
 * 現在ログイン中のユーザー情報。GET /auth/me が返す形。
 *
 * snake_case のモデル属性を camelCase で JSON 出力するよう alias を効かせる
 * （Frontend の Hey API 生成型もそのまま camelCase になる）。
 */
export type UserResponse = {
    /**
     * Displayname
     */
    displayName: string;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Id
     */
    id: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
    /**
     * Input
     */
    input?: unknown;
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type ListMyGenerationsApiMeGenerationsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
    };
    url: '/api/me/generations';
};

export type ListMyGenerationsApiMeGenerationsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListMyGenerationsApiMeGenerationsGetError = ListMyGenerationsApiMeGenerationsGetErrors[keyof ListMyGenerationsApiMeGenerationsGetErrors];

export type ListMyGenerationsApiMeGenerationsGetResponses = {
    /**
     * Successful Response
     */
    200: MeGenerationsListResponse;
};

export type ListMyGenerationsApiMeGenerationsGetResponse = ListMyGenerationsApiMeGenerationsGetResponses[keyof ListMyGenerationsApiMeGenerationsGetResponses];

export type CancelMyGenerationApiMeGenerationsRequestIdCancelPostData = {
    body?: never;
    path: {
        /**
         * Request Id
         */
        request_id: string;
    };
    query?: never;
    url: '/api/me/generations/{request_id}/cancel';
};

export type CancelMyGenerationApiMeGenerationsRequestIdCancelPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CancelMyGenerationApiMeGenerationsRequestIdCancelPostError = CancelMyGenerationApiMeGenerationsRequestIdCancelPostErrors[keyof CancelMyGenerationApiMeGenerationsRequestIdCancelPostErrors];

export type CancelMyGenerationApiMeGenerationsRequestIdCancelPostResponses = {
    /**
     * Successful Response
     */
    200: GenerationRequestCancelResponse;
};

export type CancelMyGenerationApiMeGenerationsRequestIdCancelPostResponse = CancelMyGenerationApiMeGenerationsRequestIdCancelPostResponses[keyof CancelMyGenerationApiMeGenerationsRequestIdCancelPostResponses];

export type RetryMyGenerationApiMeGenerationsRequestIdRetryPostData = {
    body?: never;
    path: {
        /**
         * Request Id
         */
        request_id: string;
    };
    query?: never;
    url: '/api/me/generations/{request_id}/retry';
};

export type RetryMyGenerationApiMeGenerationsRequestIdRetryPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RetryMyGenerationApiMeGenerationsRequestIdRetryPostError = RetryMyGenerationApiMeGenerationsRequestIdRetryPostErrors[keyof RetryMyGenerationApiMeGenerationsRequestIdRetryPostErrors];

export type RetryMyGenerationApiMeGenerationsRequestIdRetryPostResponses = {
    /**
     * Successful Response
     */
    202: GenerationRequestRetryResponse;
};

export type RetryMyGenerationApiMeGenerationsRequestIdRetryPostResponse = RetryMyGenerationApiMeGenerationsRequestIdRetryPostResponses[keyof RetryMyGenerationApiMeGenerationsRequestIdRetryPostResponses];

export type GetMyStatsApiMeStatsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/me/stats';
};

export type GetMyStatsApiMeStatsGetResponses = {
    /**
     * Successful Response
     */
    200: MeStatsResponse;
};

export type GetMyStatsApiMeStatsGetResponse = GetMyStatsApiMeStatsGetResponses[keyof GetMyStatsApiMeStatsGetResponses];

export type GetMyWeaknessApiMeWeaknessGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/me/weakness';
};

export type GetMyWeaknessApiMeWeaknessGetResponses = {
    /**
     * Successful Response
     */
    200: MeWeaknessResponse;
};

export type GetMyWeaknessApiMeWeaknessGetResponse = GetMyWeaknessApiMeWeaknessGetResponses[keyof GetMyWeaknessApiMeWeaknessGetResponses];

export type ListProblemsApiProblemsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Category
         *
         * カテゴリで絞り込み
         */
        category?: ProblemCategory | null;
        /**
         * Difficulty
         *
         * 難易度で絞り込み
         */
        difficulty?: ProblemDifficulty | null;
        /**
         * Page
         *
         * ページ番号（1 始まり）
         */
        page?: number;
        /**
         * Page Size
         *
         * 1 ページあたりの件数（上限 1000）
         */
        page_size?: number;
    };
    url: '/api/problems';
};

export type ListProblemsApiProblemsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListProblemsApiProblemsGetError = ListProblemsApiProblemsGetErrors[keyof ListProblemsApiProblemsGetErrors];

export type ListProblemsApiProblemsGetResponses = {
    /**
     * Successful Response
     */
    200: ProblemListResponse;
};

export type ListProblemsApiProblemsGetResponse = ListProblemsApiProblemsGetResponses[keyof ListProblemsApiProblemsGetResponses];

export type RequestProblemGenerationApiProblemsGeneratePostData = {
    body: ProblemGenerateRequest;
    path?: never;
    query?: never;
    url: '/api/problems/generate';
};

export type RequestProblemGenerationApiProblemsGeneratePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RequestProblemGenerationApiProblemsGeneratePostError = RequestProblemGenerationApiProblemsGeneratePostErrors[keyof RequestProblemGenerationApiProblemsGeneratePostErrors];

export type RequestProblemGenerationApiProblemsGeneratePostResponses = {
    /**
     * Successful Response
     */
    202: ProblemGenerateAcceptedResponse;
};

export type RequestProblemGenerationApiProblemsGeneratePostResponse = RequestProblemGenerationApiProblemsGeneratePostResponses[keyof RequestProblemGenerationApiProblemsGeneratePostResponses];

export type GetProblemGenerationStatusApiProblemsGenerateRequestIdGetData = {
    body?: never;
    path: {
        /**
         * Request Id
         *
         * 生成リクエストの ID
         */
        request_id: string;
    };
    query?: never;
    url: '/api/problems/generate/{request_id}';
};

export type GetProblemGenerationStatusApiProblemsGenerateRequestIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetProblemGenerationStatusApiProblemsGenerateRequestIdGetError = GetProblemGenerationStatusApiProblemsGenerateRequestIdGetErrors[keyof GetProblemGenerationStatusApiProblemsGenerateRequestIdGetErrors];

export type GetProblemGenerationStatusApiProblemsGenerateRequestIdGetResponses = {
    /**
     * Successful Response
     */
    200: ProblemGenerateStatusResponse;
};

export type GetProblemGenerationStatusApiProblemsGenerateRequestIdGetResponse = GetProblemGenerationStatusApiProblemsGenerateRequestIdGetResponses[keyof GetProblemGenerationStatusApiProblemsGenerateRequestIdGetResponses];

export type GetProblemDetailApiProblemsProblemIdGetData = {
    body?: never;
    path: {
        /**
         * Problem Id
         *
         * 問題の ID
         */
        problem_id: string;
    };
    query?: never;
    url: '/api/problems/{problem_id}';
};

export type GetProblemDetailApiProblemsProblemIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetProblemDetailApiProblemsProblemIdGetError = GetProblemDetailApiProblemsProblemIdGetErrors[keyof GetProblemDetailApiProblemsProblemIdGetErrors];

export type GetProblemDetailApiProblemsProblemIdGetResponses = {
    /**
     * Successful Response
     */
    200: ProblemDetailResponse;
};

export type GetProblemDetailApiProblemsProblemIdGetResponse = GetProblemDetailApiProblemsProblemIdGetResponses[keyof GetProblemDetailApiProblemsProblemIdGetResponses];

export type ListMySubmissionsApiSubmissionsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Pagesize
         */
        pageSize?: number;
    };
    url: '/api/submissions';
};

export type ListMySubmissionsApiSubmissionsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListMySubmissionsApiSubmissionsGetError = ListMySubmissionsApiSubmissionsGetErrors[keyof ListMySubmissionsApiSubmissionsGetErrors];

export type ListMySubmissionsApiSubmissionsGetResponses = {
    /**
     * Successful Response
     */
    200: SubmissionsListResponse;
};

export type ListMySubmissionsApiSubmissionsGetResponse = ListMySubmissionsApiSubmissionsGetResponses[keyof ListMySubmissionsApiSubmissionsGetResponses];

export type SubmitAnswerApiSubmissionsPostData = {
    body: SubmissionCreateRequest;
    path?: never;
    query?: never;
    url: '/api/submissions';
};

export type SubmitAnswerApiSubmissionsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SubmitAnswerApiSubmissionsPostError = SubmitAnswerApiSubmissionsPostErrors[keyof SubmitAnswerApiSubmissionsPostErrors];

export type SubmitAnswerApiSubmissionsPostResponses = {
    /**
     * Successful Response
     */
    202: SubmissionAcceptedResponse;
};

export type SubmitAnswerApiSubmissionsPostResponse = SubmitAnswerApiSubmissionsPostResponses[keyof SubmitAnswerApiSubmissionsPostResponses];

export type GetSubmissionApiSubmissionsSubmissionIdGetData = {
    body?: never;
    path: {
        /**
         * Submission Id
         *
         * 解答 ID
         */
        submission_id: string;
    };
    query?: never;
    url: '/api/submissions/{submission_id}';
};

export type GetSubmissionApiSubmissionsSubmissionIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSubmissionApiSubmissionsSubmissionIdGetError = GetSubmissionApiSubmissionsSubmissionIdGetErrors[keyof GetSubmissionApiSubmissionsSubmissionIdGetErrors];

export type GetSubmissionApiSubmissionsSubmissionIdGetResponses = {
    /**
     * Successful Response
     */
    200: SubmissionStatusResponse;
};

export type GetSubmissionApiSubmissionsSubmissionIdGetResponse = GetSubmissionApiSubmissionsSubmissionIdGetResponses[keyof GetSubmissionApiSubmissionsSubmissionIdGetResponses];

export type StartGithubOauthAuthGithubGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Next
         */
        next?: string | null;
    };
    url: '/auth/github';
};

export type StartGithubOauthAuthGithubGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StartGithubOauthAuthGithubGetError = StartGithubOauthAuthGithubGetErrors[keyof StartGithubOauthAuthGithubGetErrors];

export type GithubCallbackAuthGithubCallbackGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Code
         */
        code?: string | null;
        /**
         * State
         */
        state?: string | null;
        /**
         * Error
         */
        error?: string | null;
    };
    url: '/auth/github/callback';
};

export type GithubCallbackAuthGithubCallbackGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GithubCallbackAuthGithubCallbackGetError = GithubCallbackAuthGithubCallbackGetErrors[keyof GithubCallbackAuthGithubCallbackGetErrors];

export type LogoutAuthLogoutPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type LogoutAuthLogoutPostResponses = {
    /**
     * ログアウト成功（ボディなし）
     */
    204: void;
};

export type LogoutAuthLogoutPostResponse = LogoutAuthLogoutPostResponses[keyof LogoutAuthLogoutPostResponses];

export type GetMeAuthMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type GetMeAuthMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type GetMeAuthMeGetResponse = GetMeAuthMeGetResponses[keyof GetMeAuthMeGetResponses];

export type ListHealthChecksHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type ListHealthChecksHealthGetResponses = {
    /**
     * Response List Health Checks Health Get
     *
     * Successful Response
     */
    200: Array<HealthCheckResponse>;
};

export type ListHealthChecksHealthGetResponse = ListHealthChecksHealthGetResponses[keyof ListHealthChecksHealthGetResponses];

export type CreateHealthCheckHealthPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type CreateHealthCheckHealthPostResponses = {
    /**
     * Successful Response
     */
    200: HealthCheckResponse;
};

export type CreateHealthCheckHealthPostResponse = CreateHealthCheckHealthPostResponses[keyof CreateHealthCheckHealthPostResponses];

export type HealthzHealthzGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/healthz';
};

export type HealthzHealthzGetResponses = {
    /**
     * Response Healthz Healthz Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type HealthzHealthzGetResponse = HealthzHealthzGetResponses[keyof HealthzHealthzGetResponses];
