// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * GenerationRequestCancelResponse
 *
 * キャンセル後の最終状態。
 */
export const zGenerationRequestCancelResponse = z.object({
    id: z.uuid(),
    status: z.literal('canceled')
});

/**
 * GenerationRequestRetryResponse
 *
 * 再試行で作られた新規 generation_request の最小情報。
 */
export const zGenerationRequestRetryResponse = z.object({
    id: z.uuid(),
    retryOf: z.uuid(),
    status: z.literal('pending')
});

/**
 * GenerationRequestSummary
 *
 * 生成リクエスト履歴の 1 行分。
 */
export const zGenerationRequestSummary = z.object({
    category: z.string(),
    completedAt: z.iso.datetime().nullish(),
    createdAt: z.iso.datetime(),
    difficulty: z.string(),
    id: z.uuid(),
    producedProblemId: z.uuid().nullish(),
    promptVersion: z.string().nullish(),
    retryCount: z.int().gte(0),
    retryOf: z.uuid().nullish(),
    status: z.enum([
        'pending',
        'completed',
        'failed',
        'canceled'
    ])
});

/**
 * GenerationStatus
 */
export const zGenerationStatus = z.enum([
    'pending',
    'completed',
    'failed'
]);

/**
 * HealthCheckResponse
 */
export const zHealthCheckResponse = z.object({
    created_at: z.iso.datetime(),
    id: z.uuid()
});

/**
 * MeCategoryStat
 *
 * カテゴリ別の解答数・正解数・正答率。
 */
export const zMeCategoryStat = z.object({
    accuracy: z.number().gte(0).lte(1),
    attempts: z.int().gte(0),
    category: z.string(),
    correct: z.int().gte(0)
});

/**
 * MeGenerationsListResponse
 *
 * 生成履歴一覧 + ページネーション情報。
 */
export const zMeGenerationsListResponse = z.object({
    items: z.array(zGenerationRequestSummary),
    page: z.int().gte(1),
    pageSize: z.int().gte(1),
    totalPages: z.int().gte(0)
});

/**
 * MeStatsResponse
 *
 * 全期間の正答率 + カテゴリ別習熟度。
 */
export const zMeStatsResponse = z.object({
    accuracy: z.number().gte(0).lte(1),
    byCategory: z.array(zMeCategoryStat),
    correct: z.int().gte(0),
    total: z.int().gte(0)
});

/**
 * MeWeakCategoryItem
 *
 * 弱点に該当するカテゴリ 1 件。
 */
export const zMeWeakCategoryItem = z.object({
    accuracy: z.number().gte(0).lte(1),
    attempts: z.int().gte(0),
    category: z.string(),
    correct: z.int().gte(0)
});

/**
 * MeWeaknessResponse
 *
 * 弱点カテゴリ Top N。
 */
export const zMeWeaknessResponse = z.object({
    weakCategories: z.array(zMeWeakCategoryItem)
});

/**
 * ProblemCategory
 */
export const zProblemCategory = z.enum([
    'string',
    'array',
    'recursion',
    'async',
    'type-puzzle'
]);

/**
 * ProblemDifficulty
 */
export const zProblemDifficulty = z.enum([
    'easy',
    'medium',
    'hard'
]);

/**
 * ProblemExample
 *
 * 画面表示用の入出力例。input / output は表示用の文字列。
 */
export const zProblemExample = z.object({
    input: z.string(),
    output: z.string()
});

/**
 * ProblemDetailResponse
 *
 * 問題詳細。テストケースの一部のみ examples として公開する。
 */
export const zProblemDetailResponse = z.object({
    category: zProblemCategory,
    description: z.string(),
    difficulty: zProblemDifficulty,
    examples: z.array(zProblemExample),
    id: z.uuid(),
    title: z.string()
});

/**
 * ProblemGenerateAcceptedResponse
 *
 * 生成リクエスト受付完了。クライアントは requestId でポーリングを始める。
 */
export const zProblemGenerateAcceptedResponse = z.object({
    requestId: z.uuid(),
    status: z.literal('pending').optional().default('pending')
});

/**
 * ProblemGenerateRequest
 *
 * 問題生成リクエストの入力。
 *
 * category / difficulty とも Literal 縛りで MVP の許容値以外は 422 を返す
 * （バリデーションは Pydantic が SSoT、problem-generation.md §バリデーション）。
 */
export const zProblemGenerateRequest = z.object({
    category: zProblemCategory,
    difficulty: zProblemDifficulty
});

/**
 * ProblemGenerateStatusResponse
 *
 * 生成リクエストの現在ステータス。completed の時のみ problemId を含む。
 */
export const zProblemGenerateStatusResponse = z.object({
    problemId: z.uuid().nullish(),
    requestId: z.uuid(),
    status: zGenerationStatus
});

/**
 * ProblemSummaryResponse
 *
 * 問題一覧の 1 行分。タイトル / カテゴリ / 難易度のみで一覧 UI に必要十分。
 */
export const zProblemSummaryResponse = z.object({
    category: zProblemCategory,
    difficulty: zProblemDifficulty,
    id: z.uuid(),
    title: z.string()
});

/**
 * ProblemListResponse
 *
 * 問題一覧 + ページネーション情報。
 *
 * 一覧クエリ単発で SSoT が固定されており、PaginationMeta + Page の
 * 汎用化（backend.md 推奨）は 2 つ目の paginated エンドポイントが
 * 出てきた時点で行う（YAGNI、CLAUDE.md §設計原則）。
 */
export const zProblemListResponse = z.object({
    items: z.array(zProblemSummaryResponse),
    page: z.int(),
    totalPages: z.int()
});

/**
 * SubmissionAcceptedResponse
 *
 * 解答送信の受付完了。クライアントは submissionId を持って結果取得 API を叩く。
 */
export const zSubmissionAcceptedResponse = z.object({
    status: z.literal('pending').optional().default('pending'),
    submissionId: z.uuid()
});

/**
 * SubmissionCreateRequest
 *
 * 解答送信リクエスト。
 */
export const zSubmissionCreateRequest = z.object({
    code: z.string().min(1).max(100000),
    problemId: z.uuid()
});

/**
 * SubmissionFailureKind
 */
export const zSubmissionFailureKind = z.enum([
    'test_failed',
    'timeout',
    'oom',
    'syntax',
    'runtime'
]);

/**
 * SubmissionStatus
 */
export const zSubmissionStatus = z.enum([
    'pending',
    'graded',
    'failed'
]);

/**
 * SubmissionSummary
 *
 * 解答履歴の 1 行分。問題タイトルまで含めて一覧 UI に必要十分。
 */
export const zSubmissionSummary = z.object({
    gradedAt: z.iso.datetime().nullish(),
    id: z.uuid(),
    problemId: z.uuid(),
    problemTitle: z.string(),
    score: z.int().nullish(),
    status: zSubmissionStatus,
    totalCount: z.int().nullish()
});

/**
 * SubmissionTestResultItem
 *
 * 1 テストケース分の結果。passed=false の時に expected/actual/message が埋まる。
 */
export const zSubmissionTestResultItem = z.object({
    actual: z.string().nullish(),
    durationMs: z.int(),
    expected: z.string().nullish(),
    message: z.string().nullish(),
    name: z.string(),
    passed: z.boolean()
});

/**
 * SubmissionResultPayload
 *
 * 採点完了時の結果ペイロード。Worker が submissions.result に書き込む形と一致。
 */
export const zSubmissionResultPayload = z.object({
    durationMs: z.int(),
    failureKind: zSubmissionFailureKind.nullish(),
    passed: z.boolean(),
    testResults: z.array(zSubmissionTestResultItem).optional()
});

/**
 * SubmissionStatusResponse
 *
 * 解答 + 採点結果。クライアントは pending の間ポーリングする。
 */
export const zSubmissionStatusResponse = z.object({
    gradedAt: z.iso.datetime().nullish(),
    id: z.uuid(),
    problemId: z.uuid(),
    result: zSubmissionResultPayload.nullish(),
    score: z.int().nullish(),
    status: zSubmissionStatus,
    totalCount: z.int().nullish()
});

/**
 * SubmissionsListResponse
 *
 * 解答履歴一覧 + ページネーション情報。
 */
export const zSubmissionsListResponse = z.object({
    items: z.array(zSubmissionSummary),
    page: z.int(),
    pageSize: z.int(),
    totalPages: z.int()
});

/**
 * UserResponse
 *
 * 現在ログイン中のユーザー情報。GET /auth/me が返す形。
 *
 * snake_case のモデル属性を camelCase で JSON 出力するよう alias を効かせる
 * （Frontend の Hey API 生成型もそのまま camelCase になる）。
 */
export const zUserResponse = z.object({
    displayName: z.string(),
    email: z.string().nullish(),
    id: z.uuid()
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
    ctx: z.record(z.string(), z.unknown()).optional(),
    input: z.unknown().optional(),
    loc: z.array(z.union([z.string(), z.int()])),
    msg: z.string(),
    type: z.string()
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
    detail: z.array(zValidationError).optional()
});

export const zListMyGenerationsApiMeGenerationsGetQuery = z.object({
    page: z.int().gte(1).optional().default(1)
});

/**
 * Successful Response
 */
export const zListMyGenerationsApiMeGenerationsGetResponse = zMeGenerationsListResponse;

export const zCancelMyGenerationApiMeGenerationsRequestIdCancelPostPath = z.object({
    request_id: z.uuid()
});

/**
 * Successful Response
 */
export const zCancelMyGenerationApiMeGenerationsRequestIdCancelPostResponse = zGenerationRequestCancelResponse;

export const zRetryMyGenerationApiMeGenerationsRequestIdRetryPostPath = z.object({
    request_id: z.uuid()
});

/**
 * Successful Response
 */
export const zRetryMyGenerationApiMeGenerationsRequestIdRetryPostResponse = zGenerationRequestRetryResponse;

/**
 * Successful Response
 */
export const zGetMyStatsApiMeStatsGetResponse = zMeStatsResponse;

/**
 * Successful Response
 */
export const zGetMyWeaknessApiMeWeaknessGetResponse = zMeWeaknessResponse;

export const zListProblemsApiProblemsGetQuery = z.object({
    category: zProblemCategory.nullish(),
    difficulty: zProblemDifficulty.nullish(),
    page: z.int().gte(1).optional().default(1)
});

/**
 * Successful Response
 */
export const zListProblemsApiProblemsGetResponse = zProblemListResponse;

export const zRequestProblemGenerationApiProblemsGeneratePostBody = zProblemGenerateRequest;

/**
 * Successful Response
 */
export const zRequestProblemGenerationApiProblemsGeneratePostResponse = zProblemGenerateAcceptedResponse;

export const zGetProblemGenerationStatusApiProblemsGenerateRequestIdGetPath = z.object({
    request_id: z.uuid()
});

/**
 * Successful Response
 */
export const zGetProblemGenerationStatusApiProblemsGenerateRequestIdGetResponse = zProblemGenerateStatusResponse;

export const zGetProblemDetailApiProblemsProblemIdGetPath = z.object({
    problem_id: z.uuid()
});

/**
 * Successful Response
 */
export const zGetProblemDetailApiProblemsProblemIdGetResponse = zProblemDetailResponse;

export const zListMySubmissionsApiSubmissionsGetQuery = z.object({
    page: z.int().gte(1).optional().default(1),
    pageSize: z.int().gte(1).lte(100).optional().default(20)
});

/**
 * Successful Response
 */
export const zListMySubmissionsApiSubmissionsGetResponse = zSubmissionsListResponse;

export const zSubmitAnswerApiSubmissionsPostBody = zSubmissionCreateRequest;

/**
 * Successful Response
 */
export const zSubmitAnswerApiSubmissionsPostResponse = zSubmissionAcceptedResponse;

export const zGetSubmissionApiSubmissionsSubmissionIdGetPath = z.object({
    submission_id: z.uuid()
});

/**
 * Successful Response
 */
export const zGetSubmissionApiSubmissionsSubmissionIdGetResponse = zSubmissionStatusResponse;

export const zStartGithubOauthAuthGithubGetQuery = z.object({
    next: z.string().nullish()
});

export const zGithubCallbackAuthGithubCallbackGetQuery = z.object({
    code: z.string().nullish(),
    state: z.string().nullish(),
    error: z.string().nullish()
});

/**
 * ログアウト成功（ボディなし）
 */
export const zLogoutAuthLogoutPostResponse = z.void();

/**
 * Successful Response
 */
export const zGetMeAuthMeGetResponse = zUserResponse;

/**
 * Response List Health Checks Health Get
 *
 * Successful Response
 */
export const zListHealthChecksHealthGetResponse = z.array(zHealthCheckResponse);

/**
 * Successful Response
 */
export const zCreateHealthCheckHealthPostResponse = zHealthCheckResponse;

/**
 * Response Healthz Healthz Get
 *
 * Successful Response
 */
export const zHealthzHealthzGetResponse = z.record(z.string(), z.string());
