// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * HealthCheckResponse
 */
export const zHealthCheckResponse = z.object({
    created_at: z.iso.datetime(),
    id: z.uuid()
});

/**
 * Response List Health Checks Health Get
 *
 * Successful Response
 */
export const zListHealthChecksHealthGetResponse = z.array(zHealthCheckResponse);

/**
 * Successful Response
 */
export const zCreateHealthCheckHealthPostResponse = zHealthCheckResponse;

/**
 * Response Healthz Healthz Get
 *
 * Successful Response
 */
export const zHealthzHealthzGetResponse = z.record(z.string(), z.string());
