// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * GenerationStatus
 */
export const zGenerationStatus = z.enum([
    'pending',
    'completed',
    'failed'
]);

/**
 * HealthCheckResponse
 */
export const zHealthCheckResponse = z.object({
    created_at: z.iso.datetime(),
    id: z.uuid()
});

/**
 * ProblemCategory
 */
export const zProblemCategory = z.enum([
    'string',
    'array',
    'recursion',
    'async',
    'type-puzzle'
]);

/**
 * ProblemDifficulty
 */
export const zProblemDifficulty = z.enum([
    'easy',
    'medium',
    'hard'
]);

/**
 * ProblemGenerateAcceptedResponse
 *
 * 生成リクエスト受付完了。クライアントは requestId でポーリングを始める。
 */
export const zProblemGenerateAcceptedResponse = z.object({
    requestId: z.uuid(),
    status: z.literal('pending').optional().default('pending')
});

/**
 * ProblemGenerateRequest
 *
 * 問題生成リクエストの入力。
 *
 * category / difficulty とも Literal 縛りで MVP の許容値以外は 422 を返す
 * （バリデーションは Pydantic が SSoT、problem-generation.md §バリデーション）。
 */
export const zProblemGenerateRequest = z.object({
    category: zProblemCategory,
    difficulty: zProblemDifficulty
});

/**
 * ProblemGenerateStatusResponse
 *
 * 生成リクエストの現在ステータス。completed の時のみ problemId を含む。
 */
export const zProblemGenerateStatusResponse = z.object({
    problemId: z.uuid().nullish(),
    requestId: z.uuid(),
    status: zGenerationStatus
});

/**
 * UserResponse
 *
 * 現在ログイン中のユーザー情報。GET /auth/me が返す形。
 *
 * snake_case のモデル属性を camelCase で JSON 出力するよう alias を効かせる
 * （Frontend の Hey API 生成型もそのまま camelCase になる）。
 */
export const zUserResponse = z.object({
    displayName: z.string(),
    email: z.string().nullish(),
    id: z.uuid()
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
    ctx: z.record(z.string(), z.unknown()).optional(),
    input: z.unknown().optional(),
    loc: z.array(z.union([z.string(), z.int()])),
    msg: z.string(),
    type: z.string()
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
    detail: z.array(zValidationError).optional()
});

export const zStartGithubOauthAuthGithubGetQuery = z.object({
    next: z.string().nullish()
});

export const zGithubCallbackAuthGithubCallbackGetQuery = z.object({
    code: z.string().nullish(),
    state: z.string().nullish(),
    error: z.string().nullish()
});

/**
 * ログアウト成功（ボディなし）
 */
export const zLogoutAuthLogoutPostResponse = z.void();

/**
 * Successful Response
 */
export const zGetMeAuthMeGetResponse = zUserResponse;

/**
 * Response List Health Checks Health Get
 *
 * Successful Response
 */
export const zListHealthChecksHealthGetResponse = z.array(zHealthCheckResponse);

/**
 * Successful Response
 */
export const zCreateHealthCheckHealthPostResponse = zHealthCheckResponse;

/**
 * Response Healthz Healthz Get
 *
 * Successful Response
 */
export const zHealthzHealthzGetResponse = z.record(z.string(), z.string());

export const zRequestProblemGenerationProblemsGeneratePostBody = zProblemGenerateRequest;

/**
 * Successful Response
 */
export const zRequestProblemGenerationProblemsGeneratePostResponse = zProblemGenerateAcceptedResponse;

export const zGetProblemGenerationStatusProblemsGenerateRequestIdGetPath = z.object({
    request_id: z.uuid()
});

/**
 * Successful Response
 */
export const zGetProblemGenerationStatusProblemsGenerateRequestIdGetResponse = zProblemGenerateStatusResponse;
